### ISSUE TITLE
Integration with UR Codec

### ISSUE THREAD

**Issue by Xpipe** [Elnaril/uniswap-smart-path#3]
Hi, really great idea having this tool. I know it is a fairly isolated problem but I am struggling using this tool with your UR Codec, in that how do I know based on calculating the path which UR Codec to use for the uniswap V2 or V3 pool. It would be cool if there was an integration test tutorial with both tools but I understand the reason for there not being as they are different libs!

Also is it best practise to use permit2 router for all swaps currently?

Thank you for creating such great tools 🙂

**Comment by Elnaril** [comment]
Hello!

> It would be cool if there was an integration test tutorial with both tools

Having an integration test or even just an example showing how to use the uniswap-smart-path results with the UR codec would be a great addition indeed!
I'm a bit too busy at the moment, but I'll write one when I get some time.

Basically, the idea is as follow: 
- an uniswap-smart-path result gives you
  - a path, for ex: ('0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2')
  - a UR function, for ex: 'V2_SWAP_EXACT_IN'
  - an estimate
- You use the UR codec method corresponding to the function, so for ex:  `v2_swap_exact_in()` (or `v2_swap_exact_in_from_balance()`)
- one of these method's parameters is the path
- you use the estimate to calculate the min out amount you wish


> Also is it best practise to use permit2 router for all swaps currently?

Sig-based approvals brings some nice improvements (less gas usage, more convenient, expiration, ...), but being more convenient might also makes a user be less careful when signing an approval than signing _and_ sending an approval transaction. So always be sure to be on a leggit webapp and double-check what you sign to avoid a phishing attack.
Now if you build yourself the transaction, you know what you sign, and what protocol you approve, so phishing should not be a major risk.

> Thank you for creating such great tools

Happy you find my libs useful! :) Happy coding!

**Comment by Xpipe** [comment]
Excellent, thank you very much, this helps :)

**Comment by Elnaril** [comment]
Great! :)
